{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: op-db
    component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
      name: postgres
  selector:
    app: op-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresql.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: op-db
    component: postgresql
spec:
  serviceName: {{ .Values.postgresql.service.name }}
  replicas: 1
  selector:
    matchLabels:
      app: op-db
  template:
    metadata:
      labels:
        app: op-db
    spec:
{{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 8 }}
{{- end }}
      containers:
        - name: postgres
          image: {{ if .Values.global.registry }}{{ .Values.global.registry }}/{{ end }}{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
          ports:
            - containerPort: {{ .Values.postgresql.service.port }}
              name: postgres
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.postgresql.user }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.postgresql.user }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
{{ toYaml .Values.postgresql.resources | indent 12 }}
{{- if .Values.postgresql.tolerations }}
      tolerations:
{{ toYaml .Values.postgresql.tolerations | indent 8 }}
{{- end }}
{{- if .Values.postgresql.affinity }}
      affinity:
{{ toYaml .Values.postgresql.affinity | indent 8 }}
{{- end }}
{{- if .Values.postgresql.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.postgresql.persistence.storageClass }}
        storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
{{- end }}
