{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.worker.service.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: op-worker
    component: worker
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: {{ .Values.worker.service.port }}
      name: http
  selector:
    app: op-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.service.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: op-worker
    component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: op-worker
  template:
    metadata:
      labels:
        app: op-worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}
          ports:
            - containerPort: {{ .Values.worker.service.port }}
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: openpanel-config
                  key: NODE_ENV
            - name: SELF_HOSTED
              valueFrom:
                configMapKeyRef:
                  name: openpanel-config
                  key: SELF_HOSTED
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: openpanel-secrets
                  key: DATABASE_URL
            - name: DATABASE_URL_DIRECT
              valueFrom:
                secretKeyRef:
                  name: openpanel-secrets
                  key: DATABASE_URL_DIRECT
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: openpanel-secrets
                  key: REDIS_URL
            - name: CLICKHOUSE_URL
              valueFrom:
                secretKeyRef:
                  name: openpanel-secrets
                  key: CLICKHOUSE_URL
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: openpanel-config
                  key: API_URL
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.worker.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.worker.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
{{- if .Values.worker.tolerations }}
      tolerations:
{{ toYaml .Values.worker.tolerations | indent 8 }}
{{- end }}
      initContainers:
        - name: wait-for-api
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until wget -q -O- http://{{ .Values.api.service.name }}:{{ .Values.api.service.port }}/healthcheck; do
                echo "Waiting for API..."
                sleep 2
              done
              echo "API is ready!"
{{- end }}
